
# Workflow for testing this repo on github
# Only the ros folder is tested
# The gengo library requires a bunch of ros libraries; we could do this as a future improvement
# The other test libraries require some maintenance

name: RosGoTest

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Go get
      run: |
        go env
        go get -d ./...

    - name: Test
      run: |
        cd ros
        go test -v ./...